"""从 git 历史生成版本号与编译时间，供程序与 PyInstaller 使用。

触发方式：
- 本地打包：build_exe.ps1 会自动调用
- GitHub Actions：release workflow 中调用
"""

import subprocess
from datetime import datetime, timezone
from pathlib import Path


def get_git_version() -> str:
    """优先取当前提交对应的 tag；没有 tag 则返回短 commit hash。"""
    try:
        tag = subprocess.check_output(
            ["git", "describe", "--tags", "--exact-match"],
            text=True,
            stderr=subprocess.DEVNULL,
        ).strip()
        if tag:
            return tag
    except subprocess.CalledProcessError:
        pass

    try:
        commit = subprocess.check_output(
            ["git", "rev-parse", "--short", "HEAD"],
            text=True,
            stderr=subprocess.DEVNULL,
        ).strip()
        if commit:
            return commit
    except subprocess.CalledProcessError:
        pass

    return "unknown"


def main() -> None:
    version = get_git_version()
    build_time = datetime.now(timezone.utc).isoformat()

    root = Path(__file__).resolve().parent.parent
    pkg_dir = root / "wavepack_maker"
    pkg_dir.mkdir(exist_ok=True)

    # 写入程序内可读取的版本模块
    version_py = pkg_dir / "_version.py"
    version_py.write_text(
        f"""# Auto-generated by scripts/gen_version.py
__version__ = {version!r}
__build_time__ = {build_time!r}
""",
        encoding="utf-8",
    )

    # 生成 PyInstaller VSVersionInfo 文件（Windows exe 属性）
    build_dir = root / "build"
    build_dir.mkdir(exist_ok=True)
    vi_file = build_dir / "version_info.txt"
    vi_file.write_text(
        f"""# UTF-8
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=(0, 0, 0, 0),
    prodvers=(0, 0, 0, 0),
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo(
      [
      StringTable(
        '080404b0',
        [StringStruct('CompanyName', 'Fmil'),
        StringStruct('FileDescription', 'WavePack Maker - 音色打包编辑工具'),
        StringStruct('FileVersion', '{version}'),
        StringStruct('InternalName', 'WavePackMaker'),
        StringStruct('LegalCopyright', 'Fmil <fmil123@qq.com>'),
        StringStruct('OriginalFilename', 'WavePackMaker.exe'),
        StringStruct('ProductName', 'WavePack Maker'),
        StringStruct('ProductVersion', '{version}')])
      ]),
    VarFileInfo([VarStruct('Translation', [2052, 1200])])
  ]
)
""",
        encoding="utf-8",
    )

    print(f"version={version}, build_time={build_time}")


if __name__ == "__main__":
    main()
